version: "3.8"

services:
  redis-service:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  nginx-service:
    image: nginx:alpine
    container_name: nginx-loadbalancer-container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80" # Expose this to your frontend<host:container>
    depends_on:
      - broker-service1
      - broker-service2

  broker-service1:
    build: ./backend/broker
    container_name: broker-container1
    # ports:
    #   - "8081:8080"
    depends_on:
      - redis-service

  broker-service2:
    build: ./backend/broker
    container_name: broker-container2
    # ports:
    #   - "8082:8080"  # Local debug port (optional)
    depends_on:
      - redis-service

  publisher-service1:
    build: ./backend/publisher
    container_name: publisher-container1
    depends_on:
      - redis-service
    environment:
      - timeout=1000

  publisher-service2:
    build: ./backend/publisher
    container_name: publisher-container2
    depends_on:
      - redis-service
    environment:
      - timeout=1500

  publisher-service3:
    build: ./backend/publisher
    container_name: publisher-container3
    depends_on:
      - redis-service
    environment:
      - timeout=2000

  publisher-service4:
    build: ./backend/publisher
    container_name: publisher-container4
    depends_on:
      - redis-service
    environment:
      - timeout=3000

  # frontend-service:
  #   build: ./frontend
  #   container_name: frontend-container
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - broker-service
  #     - publisher-service
  #     - redis-service
