version: "3.8"

services:
  redis-service:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  broker-service:
    build: ./backend/broker
    container_name: broker-container
    ports:
      - "8080:8080"
    depends_on:
      - redis-service

  publisher-service1:
    build: ./backend/publisher
    container_name: publisher-container1
    depends_on:
      - redis-service
    environment:
      - timeout=1000

  publisher-service2:
    build: ./backend/publisher
    container_name: publisher-container2
    depends_on:
      - redis-service
    environment:
      - timeout=1500

  publisher-service3:
    build: ./backend/publisher
    container_name: publisher-container3
    depends_on:
      - redis-service
    environment:
      - timeout=2000

  publisher-service4:
    build: ./backend/publisher
    container_name: publisher-container4
    depends_on:
      - redis-service
    environment:
      - timeout=3000

  # frontend-service:
  #   build: ./frontend
  #   container_name: frontend-container
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - broker-service
  #     - publisher-service
  #     - redis-service
